"""
report_builder.py
-----------------
Takes all agent outputs and builds a final professional report.
Supports Markdown and HTML output.

Place this in: /core/report_builder.py
"""

from datetime import datetime


class ReportBuilder:
    """
    Assembles agent outputs into a final formatted report.
    """

    # Section order for the final report
    SECTION_ORDER = [
        "CEO (Chief Executive Officer)",
        "CFO (Chief Financial Officer)",
        "COO (Chief Operating Officer)",
        "CTO (Chief Technology Officer)",
        "HR Manager (Human Resources)",
        "Sales Manager",
        "Project Manager",
    ]

    # ------------------------------------------------------------------
    # MARKDOWN REPORT
    # ------------------------------------------------------------------

    def build_markdown(self, file_name: str, agent_outputs: list) -> str:
        """
        Returns the complete report as a Markdown string.
        """
        now = datetime.now().strftime("%Y-%m-%d %H:%M")
        lines = []

        # Header
        lines.append(f"# 📋 Multi-Agent Business Analysis Report")
        lines.append(f"")
        lines.append(f"**Document Analyzed:** `{file_name}`  ")
        lines.append(f"**Generated:** {now}  ")
        lines.append(f"**Agents Used:** {len(agent_outputs)}")
        lines.append(f"")
        lines.append("---")
        lines.append("")

        # Table of Contents
        lines.append("## 📑 Table of Contents")
        lines.append("")
        for output in self._sorted(agent_outputs):
            anchor = output["role"].lower().replace(" ", "-").replace("(", "").replace(")", "")
            lines.append(f"- [{output['emoji']} {output['role']}](#{anchor})")
        lines.append(f"- [🔥 Final Recommendations](#final-recommendations)")
        lines.append("")
        lines.append("---")
        lines.append("")

        # Each agent section
        for output in self._sorted(agent_outputs):
            role   = output["role"]
            emoji  = output["emoji"]
            text   = output["analysis"]
            status = "" if output["success"] else " ⚠️ *Analysis incomplete*"

            lines.append(f"## {emoji} {role}")
            lines.append(status)
            lines.append("")
            lines.append(text)
            lines.append("")
            lines.append("---")
            lines.append("")

        # Final Recommendations section
        lines.append("## 🔥 Final Recommendations")
        lines.append("")
        lines.append(self._generate_recommendations(agent_outputs))
        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append("*Report generated by Multi-Agent AI System*")

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # HTML REPORT
    # ------------------------------------------------------------------

    def build_html(self, file_name: str, agent_outputs: list) -> str:
        """
        Returns the complete report as an HTML string (nicely styled).
        """
        now = datetime.now().strftime("%Y-%m-%d %H:%M")

        sections_html = ""
        for output in self._sorted(agent_outputs):
            # Convert markdown-style headers inside analysis to HTML
            analysis_html = self._md_to_basic_html(output["analysis"])
            color = "#27ae60" if output["success"] else "#e74c3c"
            sections_html += f"""
            <div class="section">
                <div class="section-header" style="border-left: 5px solid {color};">
                    <span class="emoji">{output['emoji']}</span>
                    <span class="role-title">{output['role']}</span>
                </div>
                <div class="section-body">
                    {analysis_html}
                </div>
            </div>
            """

        recommendations = self._md_to_basic_html(self._generate_recommendations(agent_outputs))

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Business Analysis Report — {file_name}</title>
    <style>
        * {{ box-sizing: border-box; margin: 0; padding: 0; }}
        body {{
            font-family: 'Segoe UI', sans-serif;
            background: #f4f6f9;
            color: #333;
            padding: 30px;
        }}
        .report-container {{
            max-width: 1000px;
            margin: auto;
            background: white;
            border-radius: 12px;
            box-shadow: 0 4px 20px rgba(0,0,0,0.08);
            overflow: hidden;
        }}
        .report-header {{
            background: linear-gradient(135deg, #1a1a2e, #16213e);
            color: white;
            padding: 40px;
            text-align: center;
        }}
        .report-header h1 {{ font-size: 2em; margin-bottom: 10px; }}
        .report-header .meta {{ opacity: 0.7; font-size: 0.9em; }}
        .report-body {{ padding: 30px; }}
        .section {{
            margin-bottom: 30px;
            border-radius: 8px;
            border: 1px solid #eee;
            overflow: hidden;
        }}
        .section-header {{
            background: #f8f9fa;
            padding: 15px 20px;
            display: flex;
            align-items: center;
            gap: 12px;
        }}
        .emoji {{ font-size: 1.8em; }}
        .role-title {{ font-size: 1.2em; font-weight: 700; color: #1a1a2e; }}
        .section-body {{
            padding: 20px;
            line-height: 1.7;
        }}
        .section-body h2 {{ 
            font-size: 1em; 
            font-weight: 700; 
            color: #2c3e50; 
            margin: 15px 0 5px 0;
            border-bottom: 1px solid #eee;
            padding-bottom: 3px;
        }}
        .section-body ul {{ margin-left: 20px; margin-top: 5px; }}
        .section-body li {{ margin-bottom: 4px; }}
        .final-section {{
            background: linear-gradient(135deg, #f39c12, #e74c3c);
            color: white;
            padding: 30px;
            border-radius: 8px;
            margin-top: 20px;
        }}
        .final-section h2 {{ font-size: 1.5em; margin-bottom: 15px; }}
        .footer {{
            text-align: center;
            padding: 20px;
            color: #999;
            font-size: 0.85em;
        }}
    </style>
</head>
<body>
    <div class="report-container">
        <div class="report-header">
            <h1>📋 Multi-Agent Business Analysis</h1>
            <div class="meta">
                <strong>Document:</strong> {file_name} &nbsp;|&nbsp;
                <strong>Generated:</strong> {now} &nbsp;|&nbsp;
                <strong>Agents:</strong> {len(agent_outputs)}
            </div>
        </div>
        <div class="report-body">
            {sections_html}
            <div class="final-section">
                <h2>🔥 Final Recommendations</h2>
                {recommendations}
            </div>
        </div>
        <div class="footer">Report generated by Multi-Agent AI System</div>
    </div>
</body>
</html>"""
        return html

    # ------------------------------------------------------------------
    # HELPERS
    # ------------------------------------------------------------------

    def _sorted(self, outputs: list) -> list:
        """Sort agent outputs by SECTION_ORDER."""
        def sort_key(o):
            try:
                return self.SECTION_ORDER.index(o["role"])
            except ValueError:
                return 99
        return sorted(outputs, key=sort_key)

    def _generate_recommendations(self, outputs: list) -> str:
        """
        Generates a short meta-summary recommending top actions.
        This is a simple rule-based summary (not another LLM call).
        """
        lines = [
            "Based on the combined analysis from all agents, here are the top recommendations:\n",
            "1. **Immediate Actions (0–30 days):** Address the most critical risks identified by the CEO and CFO agents. Focus on financial stability and quick operational wins.",
            "2. **Short-Term (1–3 months):** Execute the Project Manager's Phase 1 milestones. Begin hiring for the key roles identified by HR.",
            "3. **Medium-Term (3–6 months):** Implement the CTO's technical roadmap. Launch the Sales Manager's go-to-market strategy.",
            "4. **Long-Term (6–12 months):** Revisit strategic goals with CEO. Measure against KPIs defined in the PM's success metrics.",
            "",
            "> 💡 **Pro Tip:** Re-run this analysis every quarter as the business evolves.",
        ]
        return "\n".join(lines)

    def _md_to_basic_html(self, text: str) -> str:
        """
        Very basic Markdown → HTML converter for agent output.
        Handles: ## headers, **bold**, bullet points (-)
        """
        import re
        lines = text.split("\n")
        html_lines = []
        for line in lines:
            line = re.sub(r"\*\*(.*?)\*\*", r"<strong>\1</strong>", line)  # bold
            if line.startswith("## "):
                html_lines.append(f"<h2>{line[3:]}</h2>")
            elif line.startswith("# "):
                html_lines.append(f"<h2>{line[2:]}</h2>")
            elif line.startswith("- ") or line.startswith("* "):
                html_lines.append(f"<li>{line[2:]}</li>")
            elif line.startswith("> "):
                html_lines.append(f"<blockquote>{line[2:]}</blockquote>")
            elif line.strip() == "":
                html_lines.append("<br>")
            else:
                html_lines.append(f"<p>{line}</p>")
        return "\n".join(html_lines)

    def save_markdown(self, content: str, path: str) -> None:
        """Save the markdown report to a file."""
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"[ReportBuilder] Markdown saved to: {path}")

    def save_html(self, content: str, path: str) -> None:
        """Save the HTML report to a file."""
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"[ReportBuilder] HTML saved to: {path}")
